-- 1. SETUP & EXTENSIONS
-- Activate UUID extension for user IDs
create extension if not exists "uuid-ossp";

-- 2. USERS & PROFILES
-- Create a table for public profiles (links to Supabase auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  full_name text,
  avatar_url text,
  bio text,
  location text,
  website text,
  instagram_username text,
  twitter_username text,
  total_views bigint default 0,
  total_downloads bigint default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Policies for Profiles
create policy "Public profiles are viewable by everyone." 
  on public.profiles for select using (true);

create policy "Users can insert their own profile." 
  on public.profiles for insert with check (auth.uid() = id);

create policy "Users can update their own profile." 
  on public.profiles for update using (auth.uid() = id);

-- Trigger to handle updated_at
create or replace function public.handle_updated_at() 
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger on_profiles_updated
  before update on public.profiles
  for each row execute procedure public.handle_updated_at();

-- Trigger to automatically create a profile for every new user
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, username)
  values (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'avatar_url',
    coalesce(
      new.raw_user_meta_data->>'username', 
      split_part(new.email, '@', 1) || '_' || substring(new.id::text from 1 for 5)
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. MEDIA (Photos, Illustrations, Videos)
create type media_type as enum ('photo', 'illustration', 'video');

create table public.media (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  type media_type not null default 'photo',
  url text not null,
  thumbnail_url text, -- For videos
  title text,
  alt_text text,
  description text,
  location text,
  views_count int default 0,
  downloads_count int default 0,
  likes_count int default 0,
  width int,
  height int,
  duration text, -- format "0:00" for videos
  status text default 'published', -- published, pending, rejected
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.media enable row level security;

-- Policies for Media
create policy "Media items are viewable by everyone." 
  on public.media for select using (true);

create policy "Users can upload their own media." 
  on public.media for insert with check (auth.uid() = user_id);

create policy "Users can update their own media." 
  on public.media for update using (auth.uid() = user_id);

create policy "Users can delete their own media." 
  on public.media for delete using (auth.uid() = user_id);

create trigger on_media_updated
  before update on public.media
  for each row execute procedure public.handle_updated_at();

-- 4. TOPICS (Categories)
create table public.topics (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  description text,
  cover_image_url text, -- URL to a representative image
  total_media int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.topics enable row level security;

create policy "Topics are viewable by everyone." 
  on public.topics for select using (true);

-- (Only admins usually update topics, but for simplicity allowing read-only for now generally)

-- 5. MEDIA_TOPICS (Join Table)
create table public.media_topics (
  media_id bigint references public.media(id) on delete cascade not null,
  topic_id bigint references public.topics(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (media_id, topic_id)
);

alter table public.media_topics enable row level security;

create policy "Media topics are viewable by everyone." 
  on public.media_topics for select using (true);

-- 6. LIKES
create table public.media_likes (
  user_id uuid references auth.users not null,
  media_id bigint references public.media(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, media_id)
);

alter table public.media_likes enable row level security;

create policy "Likes are viewable by everyone." 
  on public.media_likes for select using (true);

create policy "Users can like media (insert)." 
  on public.media_likes for insert with check (auth.uid() = user_id);

create policy "Users can unlike media (delete)." 
  on public.media_likes for delete using (auth.uid() = user_id);

-- Function to increment/decrement likes_count on media when like is added/removed
create or replace function public.handle_new_like()
returns trigger as $$
begin
  update public.media
  set likes_count = likes_count + 1
  where id = new.media_id;
  return new;
end;
$$ language plpgsql;

create trigger on_like_added
  after insert on public.media_likes
  for each row execute procedure public.handle_new_like();

create or replace function public.handle_unlike()
returns trigger as $$
begin
  update public.media
  set likes_count = likes_count - 1
  where id = old.media_id;
  return old;
end;
$$ language plpgsql;

create trigger on_like_removed
  after delete on public.media_likes
  for each row execute procedure public.handle_unlike();

-- 7. COLLECTIONS (User created albums)
create table public.collections (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  title text not null,
  description text,
  is_private boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.collections enable row level security;

create policy "Public collections are viewable by everyone." 
  on public.collections for select using (is_private = false);

create policy "Users can view their own private collections." 
  on public.collections for select using (auth.uid() = user_id);

create policy "Users can create collections." 
  on public.collections for insert with check (auth.uid() = user_id);

create policy "Users can update their own collections." 
  on public.collections for update using (auth.uid() = user_id);

create policy "Users can delete their own collections." 
  on public.collections for delete using (auth.uid() = user_id);

-- Collection Items
create table public.collection_media (
  collection_id bigint references public.collections(id) on delete cascade not null,
  media_id bigint references public.media(id) on delete cascade not null,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (collection_id, media_id)
);

alter table public.collection_media enable row level security;

create policy "Public collection items are viewable." 
  on public.collection_media for select 
  using (exists (
    select 1 from public.collections 
    where id = public.collection_media.collection_id and is_private = false
  ));

create policy "Users can manage items in their collections."
  on public.collection_media for all
  using (exists (
    select 1 from public.collections 
    where id = public.collection_media.collection_id and user_id = auth.uid()
  ));


-- 8. SEED DATA (Topics and a Placeholder User)
-- Note: Replace 'PLACEHOLDER_USER_ID' with a real UUID from auth.users if you want to seed media manually via SQL.

INSERT INTO public.topics (name, slug) VALUES 
('Fond d''écran', 'wallpapers'),
('Nature', 'nature'),
('Libreville', 'libreville'),
('Culture', 'culture'),
('Faune', 'animals'),
('Plages', 'beaches'),
('Architecture', 'architecture'),
('Portrait', 'people'),
('Voyage', 'travel'),
('Textures', 'textures'),
('Affaires', 'business'),
('Mode', 'fashion')
ON CONFLICT (slug) DO NOTHING;

-- Helpful Views
create or replace view public.random_media as
  select * from public.media order by random();
