-- ============================================================================
-- JEaLiFe Pictures — historique des téléchargements
--
--   Le menu utilisateur propose « Historique téléchargements » depuis le
--   début, mais rien ne l'alimentait : `increment_downloads` (migration
--   0001) ne touchait que deux compteurs agrégés (media.downloads_count,
--   profiles.total_downloads), sans jamais consigner QUI avait téléchargé
--   QUOI. Cette table comble ce manque.
-- ============================================================================

create table public.media_downloads (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users on delete cascade,
  media_id   bigint not null references public.media(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index media_downloads_user_idx on public.media_downloads (user_id, created_at desc);
create index media_downloads_media_idx on public.media_downloads (media_id);

alter table public.media_downloads enable row level security;

-- Privé, contrairement aux j'aime (media_likes) : ce qu'on télécharge ne
-- regarde que soi.
create policy "Chacun voit son propre historique de téléchargements."
  on public.media_downloads for select using (auth.uid() = user_id);

-- Pas de policy insert : la table ne s'écrit que via increment_downloads
-- (security definer) ci-dessous, jamais directement depuis le navigateur.

create or replace function public.increment_downloads(media_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.media m
     set downloads_count = m.downloads_count + 1
   where m.id = media_id and m.status = 'published';

  update public.profiles p
     set total_downloads = p.total_downloads + 1
    from public.media m
   where m.id = media_id and p.id = m.user_id;

  -- Téléchargement anonyme : rien à consigner, personne à qui l'attribuer.
  if auth.uid() is not null then
    insert into public.media_downloads (user_id, media_id)
    values (auth.uid(), media_id);
  end if;
end;
$$;

grant execute on function public.increment_downloads(bigint) to anon, authenticated;
