-- ============================================================================
-- JEaLiFe Pictures — suspension de compte et journal d'audit admin
--   · Aujourd'hui, le seul levier contre un compte qui abuse (spam d'envois,
--     faux signalements) est de rejeter son contenu photo par photo pendant
--     qu'il continue d'en publier. `is_suspended` coupe l'accès à l'écriture
--     sans supprimer le compte ni son historique.
--   · Aucune action admin (changement de rôle, suspension, suppression de
--     contenu, résolution de signalement) n'était tracée nulle part : dès
--     qu'il y a plus d'un admin actif, "qui a fait quoi" devient une vraie
--     question sans réponse. `admin_audit_log` y répond.
--   · Portée volontairement limitée : ceci bloque les nouvelles publications
--     d'un compte suspendu (RLS/déclencheur), pas sa connexion — désactiver
--     un compte côté Supabase Auth demanderait la clé de rôle de service dans
--     une route serveur, une décision à part qui n'a pas été prise ici.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Suspension
-- ----------------------------------------------------------------------------
alter table public.profiles
  add column if not exists is_suspended boolean not null default false;

-- Étend la garde existante (migration 0004) : personne ne doit pouvoir se
-- lever sa propre suspension, pas plus qu'il ne peut déjà s'auto-promouvoir
-- admin ou se marquer vérifié.
create or replace function public.protect_profile_privileges()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is not null and not public.is_admin() then
    new.role := old.role;
    new.is_verified := old.is_verified;
    new.is_contributor := old.is_contributor;
    new.is_suspended := old.is_suspended;
  end if;
  return new;
end;
$$;

-- Bloque la publication à l'écriture plutôt que de dupliquer la règle dans
-- une policy RLS séparée : `media_before_write` est déjà l'endroit qui décide
-- du sort d'un INSERT (migrations 0004 et 0008), on y ajoute simplement ce
-- premier verrou.
create or replace function public.media_before_write()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    if exists (select 1 from public.profiles where id = new.user_id and is_suspended) then
      raise exception 'Ce compte a été suspendu et ne peut plus publier.' using errcode = '42501';
    end if;

    if not public.is_admin() then
      new.status := case
        when public.get_setting('moderation_mode') = 'manual' then 'pending'::public.media_status
        else 'published'::public.media_status
      end;
    end if;
  end if;

  new.geo_priority := public.geo_priority_for(new.country_code);

  new.orientation := case
    when new.width is null or new.height is null then null
    when new.width > new.height then 'paysage'
    when new.height > new.width then 'portrait'
    else 'carre'
  end;

  new.search_vector :=
      setweight(to_tsvector('public.fr_unaccent', coalesce(new.title, '')), 'A')
    || setweight(to_tsvector('public.fr_unaccent', array_to_string(coalesce(new.tags, '{}'), ' ')), 'A')
    || setweight(to_tsvector('public.fr_unaccent', coalesce(new.alt_text, '')), 'B')
    || setweight(to_tsvector('public.fr_unaccent', coalesce(new.location, '')), 'B')
    || setweight(to_tsvector('public.fr_unaccent', coalesce(new.city, '')), 'B')
    || setweight(to_tsvector('public.fr_unaccent',
         coalesce((select c.name_fr from public.countries c where c.code = new.country_code), '')), 'B')
    || setweight(to_tsvector('public.fr_unaccent', coalesce(new.description, '')), 'C')
    || setweight(to_tsvector('public.fr_unaccent', coalesce(new.camera, '')), 'D');

  return new;
end;
$$;

-- ----------------------------------------------------------------------------
-- 2. Journal d'audit admin
--
--    Écriture uniquement via `log_admin_action` (jamais d'insert direct
--    depuis le client) : même principe que `set_setting` (migration 0004),
--    la vérification `is_admin()` vit dans la fonction plutôt que dans une
--    policy RLS séparée à garder synchronisée.
-- ----------------------------------------------------------------------------
create table public.admin_audit_log (
  id          bigint generated by default as identity primary key,
  admin_id    uuid references auth.users on delete set null,
  action      text not null,
  target_type text not null,
  target_id   text,
  details     jsonb,
  created_at  timestamptz not null default now()
);

create index admin_audit_log_created_idx on public.admin_audit_log (created_at desc);

alter table public.admin_audit_log enable row level security;

create policy "Seuls les admins consultent le journal."
  on public.admin_audit_log for select using (public.is_admin());

create or replace function public.log_admin_action(
  p_action text,
  p_target_type text,
  p_target_id text,
  p_details jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Permission refusée.' using errcode = '42501';
  end if;

  insert into public.admin_audit_log (admin_id, action, target_type, target_id, details)
  values (auth.uid(), p_action, p_target_type, p_target_id, p_details);
end;
$$;

grant execute on function public.log_admin_action(text, text, text, jsonb) to authenticated;
