-- ============================================================================
-- JEaLiFe Pictures — vues et téléchargements : compteurs sans écriture
-- répétée sur la même ligne.
--
--   `increment_views`/`increment_downloads` (migration 0001) faisaient
--   chacune deux UPDATE synchrones (media + profiles) À CHAQUE appel, sans
--   aucune déduplication : rafraîchir une fiche photo dix fois ajoutait dix
--   vues. Ce schéma finirait par créer un point chaud — la même ligne
--   `media` mise à jour, donc verrouillée, à chaque vue — le genre de
--   problème qu'on préfère prévenir avant qu'il n'arrive plutôt que le
--   subir une fois le trafic là.
--
--   Nouveau schéma :
--     · Les vues sont d'abord journalisées dans `media_views`, avec une
--       contrainte d'unicité (média, visiteur, jour) : la déduplication se
--       fait à l'écriture (ON CONFLICT DO NOTHING), jamais par une lecture
--       préalable qui doublerait le nombre de requêtes.
--     · `increment_downloads` continue de journaliser dans
--       `media_downloads` (migration 0009, pas de déduplication — retélé-
--       charger la même image plus tard reste un téléchargement légitime),
--       mais ne touche plus aux compteurs agrégés.
--     · `media.views_count`/`downloads_count` et
--       `profiles.total_views`/`total_downloads` sont recalculés en bloc
--       par `sync_media_counters()`, appelée périodiquement (voir
--       /api/cron/sync-counters) plutôt qu'à chaque événement — un seul
--       UPDATE par ligne concernée et par cycle, quel que soit le nombre
--       de vues ou de téléchargements survenus entretemps.
--     · Colonnes `*_baseline` : `media_downloads` existe et compte déjà
--       depuis la migration 0009 alors que `downloads_count` continuait,
--       jusqu'ici, d'être incrémenté en parallèle par la même fonction —
--       sans ce point de départ, additionner le journal au compteur actuel
--       aurait compté ces téléchargements-là deux fois. Le baseline capture
--       la part de l'historique antérieure au journal (ou, pour les vues,
--       tout l'historique existant puisque `media_views` est entièrement
--       nouvelle) ; tout ce qui suit vient uniquement du journal.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Journal des vues, déduplication par (média, visiteur, jour)
-- ----------------------------------------------------------------------------
create table public.media_views (
  id         bigint generated by default as identity primary key,
  media_id   bigint not null references public.media(id) on delete cascade,
  viewer_key text not null,
  viewed_on  date not null default current_date,
  created_at timestamptz not null default now(),
  unique (media_id, viewer_key, viewed_on)
);

create index media_views_media_idx on public.media_views (media_id);

alter table public.media_views enable row level security;

-- Écriture uniquement via record_view (security definer) ; lecture réservée
-- à l'admin, comme les autres journaux internes (media_downloads, audit).
create policy "Un admin peut consulter le journal des vues."
  on public.media_views for select using (public.is_admin());

create or replace function public.record_view(media_id bigint, viewer_key text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.media_views (media_id, viewer_key)
  values (record_view.media_id, record_view.viewer_key)
  on conflict (media_id, viewer_key, viewed_on) do nothing;
end;
$$;

grant execute on function public.record_view(bigint, text) to anon, authenticated;

-- ----------------------------------------------------------------------------
-- 2. Baselines — point de départ pour ne pas perdre l'historique déjà
--    accumulé au moment de cette migration.
-- ----------------------------------------------------------------------------
alter table public.media
  add column views_count_baseline bigint not null default 0,
  add column downloads_count_baseline bigint not null default 0;

update public.media set views_count_baseline = views_count;

-- Soustrait ce que `media_downloads` compte déjà pour ce média : le reste
-- (potentiellement negatif si les deux avaient déjà divergé — greatest()
-- s'en protège) correspond aux téléchargements d'avant la migration 0009,
-- jamais journalisés.
update public.media m
   set downloads_count_baseline = greatest(
     0,
     m.downloads_count - coalesce(
       (select count(*) from public.media_downloads d where d.media_id = m.id), 0
     )
   );

alter table public.profiles
  add column total_views_baseline bigint not null default 0,
  add column total_downloads_baseline bigint not null default 0;

update public.profiles set total_views_baseline = total_views;

update public.profiles p
   set total_downloads_baseline = greatest(
     0,
     p.total_downloads - coalesce(
       (
         select count(*) from public.media_downloads d
         join public.media m on m.id = d.media_id
         where m.user_id = p.id
       ), 0
     )
   );

-- ----------------------------------------------------------------------------
-- 3. `increment_downloads` : ne touche plus aux compteurs agrégés, ne fait
--    plus que journaliser l'événement (comportement identique à la
--    migration 0009 pour la partie journal).
-- ----------------------------------------------------------------------------
create or replace function public.increment_downloads(media_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is not null then
    insert into public.media_downloads (user_id, media_id)
    values (auth.uid(), increment_downloads.media_id);
  end if;
end;
$$;

-- `increment_views` retiré : remplacée par record_view (déduplication) +
-- sync_media_counters (agrégation périodique). Les appels existants
-- passent désormais par la route /api/track-view.
drop function if exists public.increment_views(bigint);

-- ----------------------------------------------------------------------------
-- 4. Agrégation en bloc — un seul UPDATE par ligne concernée, indépendant
--    du volume d'événements survenus entretemps. `is distinct from` évite
--    d'écrire les lignes dont le total n'a pas changé depuis le dernier
--    cycle (l'immense majorité, entre deux passages).
--
--    Pas de grant à anon/authenticated : PostgREST expose en RPC toute
--    fonction accordée à ces rôles, or Postgres accorde EXECUTE à PUBLIC
--    par défaut à la création — le revoke explicite empêche qu'un visiteur
--    déclenche cette fonction à volonté. Seul le rôle service (voir
--    /api/cron/sync-counters, appelé par le cron) peut l'exécuter.
-- ----------------------------------------------------------------------------
create or replace function public.sync_media_counters()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.media m
     set views_count = m.views_count_baseline + v.n
    from (select media_id, count(*) as n from public.media_views group by media_id) v
   where m.id = v.media_id
     and m.views_count is distinct from (m.views_count_baseline + v.n);

  update public.media m
     set downloads_count = m.downloads_count_baseline + d.n
    from (select media_id, count(*) as n from public.media_downloads group by media_id) d
   where m.id = d.media_id
     and m.downloads_count is distinct from (m.downloads_count_baseline + d.n);

  update public.profiles p
     set total_views = p.total_views_baseline + v.n
    from (
      select m.user_id, count(*) as n
      from public.media_views mv join public.media m on m.id = mv.media_id
      group by m.user_id
    ) v
   where p.id = v.user_id
     and p.total_views is distinct from (p.total_views_baseline + v.n);

  update public.profiles p
     set total_downloads = p.total_downloads_baseline + d.n
    from (
      select m.user_id, count(*) as n
      from public.media_downloads md join public.media m on m.id = md.media_id
      group by m.user_id
    ) d
   where p.id = d.user_id
     and p.total_downloads is distinct from (p.total_downloads_baseline + d.n);
end;
$$;

revoke all on function public.sync_media_counters() from public;
grant execute on function public.sync_media_counters() to service_role;
