-- ============================================================================
-- JEaLiFe Pictures — activité / notifications (façon Unsplash)
--
--   Une seule table d'événements, remplie automatiquement par des
--   déclencheurs sur les tables qui portent déjà le vrai événement
--   (`media_likes`, `collection_media`, `premium_downloads`, `payouts`) —
--   jamais par du code applicatif qui pourrait oublier d'appeler une
--   fonction. Même logique que les compteurs de vues/téléchargements
--   (migration 0014) et le système de crédits (migration 0019) : la base
--   est la seule source de vérité, le client ne fait qu'afficher.
-- ============================================================================

create table public.notifications (
  id            bigint generated by default as identity primary key,
  recipient_id  uuid not null references public.profiles(id) on delete cascade,
  actor_id      uuid references public.profiles(id) on delete set null,
  type          text not null check (type in ('like', 'collection_add', 'premium_purchase', 'payout_paid')),
  -- Une notification garde son sens même si le média est retiré plus tard
  -- (l'historique reste lisible : « X a aimé votre photo », sans lien mort) ;
  -- seule la suppression DÉFINITIVE du média (pas un simple retrait/rejet,
  -- qui ne touchent jamais la ligne) fait disparaître la notification avec
  -- lui, faute de sujet à montrer.
  media_id      bigint references public.media(id) on delete cascade,
  collection_id bigint references public.collections(id) on delete set null,
  -- Détails d'appoint (titre de la collection au moment de l'ajout, montant
  -- en crédits/FCFA...) : évite une jointure supplémentaire à l'affichage et
  -- garde un texte stable même si la collection est renommée depuis.
  details       jsonb,
  read_at       timestamptz,
  created_at    timestamptz not null default now()
);

create index notifications_recipient_idx on public.notifications (recipient_id, created_at desc);
create index notifications_unread_idx on public.notifications (recipient_id) where read_at is null;

alter table public.notifications enable row level security;

create policy "Chacun consulte ses propres notifications."
  on public.notifications for select
  using (auth.uid() = recipient_id);

-- Seul le marquage « lu » passe par le client ; la création d'une ligne ne
-- peut venir que des déclencheurs `security definer` ci-dessous — aucune
-- policy insert n'existe pour un rôle client.
create policy "Chacun marque ses propres notifications comme lues."
  on public.notifications for update
  using (auth.uid() = recipient_id)
  with check (auth.uid() = recipient_id);

-- ----------------------------------------------------------------------------
-- 1. J'aime reçu
-- ----------------------------------------------------------------------------
create or replace function public.notify_on_like()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner uuid;
begin
  select user_id into v_owner from public.media where id = new.media_id;

  -- Jamais de notification pour un « j'aime » sur sa propre photo.
  if v_owner is not null and v_owner <> new.user_id then
    insert into public.notifications (recipient_id, actor_id, type, media_id)
    values (v_owner, new.user_id, 'like', new.media_id);
  end if;

  return new;
end;
$$;

drop trigger if exists trg_notify_on_like on public.media_likes;
create trigger trg_notify_on_like
after insert on public.media_likes
for each row execute function public.notify_on_like();

-- ----------------------------------------------------------------------------
-- 2. Photo ajoutée à une collection — l'exemple donné par l'utilisateur :
--    « X a ajouté votre photo dans "nom de la collection" ».
-- ----------------------------------------------------------------------------
create or replace function public.notify_on_collection_add()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_media_owner uuid;
  v_collection_owner uuid;
  v_collection_title text;
begin
  select user_id into v_media_owner from public.media where id = new.media_id;
  select user_id, title into v_collection_owner, v_collection_title
    from public.collections where id = new.collection_id;

  -- Jamais de notification pour l'ajout de sa propre photo à sa propre collection.
  if v_media_owner is not null and v_collection_owner is not null and v_media_owner <> v_collection_owner then
    insert into public.notifications (recipient_id, actor_id, type, media_id, collection_id, details)
    values (
      v_media_owner, v_collection_owner, 'collection_add', new.media_id, new.collection_id,
      jsonb_build_object('collection_title', v_collection_title)
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_notify_on_collection_add on public.collection_media;
create trigger trg_notify_on_collection_add
after insert on public.collection_media
for each row execute function public.notify_on_collection_add();

-- ----------------------------------------------------------------------------
-- 3. Vente Premium — la notification la plus importante pour un
--    contributeur, maintenant que l'argent réel entre en jeu (migration 0019).
-- ----------------------------------------------------------------------------
create or replace function public.notify_on_premium_purchase()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notifications (recipient_id, actor_id, type, media_id, details)
  values (
    new.contributor_id, new.buyer_id, 'premium_purchase', new.media_id,
    jsonb_build_object('credits_spent', new.credits_spent, 'earning_fcfa', new.contributor_earning_fcfa)
  );

  return new;
end;
$$;

drop trigger if exists trg_notify_on_premium_purchase on public.premium_downloads;
create trigger trg_notify_on_premium_purchase
after insert on public.premium_downloads
for each row execute function public.notify_on_premium_purchase();

-- ----------------------------------------------------------------------------
-- 4. Versement confirmé — `mark_payout_paid` (migration 0019) n'insère
--    jamais qu'une ligne déjà `paid` (le versement manuel a déjà eu lieu
--    par Mobile Money au moment où l'admin l'enregistre) : chaque insertion
--    est donc bien un versement confirmé, jamais une simple mise en attente.
-- ----------------------------------------------------------------------------
create or replace function public.notify_on_payout_paid()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notifications (recipient_id, actor_id, type, details)
  values (
    new.contributor_id, new.paid_by_admin_id, 'payout_paid',
    jsonb_build_object('amount_fcfa', new.amount_fcfa, 'note', new.note)
  );

  return new;
end;
$$;

drop trigger if exists trg_notify_on_payout_paid on public.payouts;
create trigger trg_notify_on_payout_paid
after insert on public.payouts
for each row execute function public.notify_on_payout_paid();
